### ISSUE TITLE
魅族pro6s  toast闪退

### ISSUE THREAD

**Issue by wp549741214** [vincent-series/smart-show#50]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
        at com.coder.zzq.smartshow.toast.compact.SafeHandler.dispatchMessage(SafeHandler.java:23)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6608)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by wp549741214** [comment]
3.1.7版本

**Comment by vincent-series** [comment]
问题已解决，请使用最新版。
