### ISSUE TITLE
求助：smart-dialog:4.0.7  Caused by: java.lang.NoSuchMethodError: No static method getVincentActivityLifecycleCallbacks()

### ISSUE THREAD

**Issue by Black-Knights** [vincent-series/smart-show#66]
import com.coder.vincent.series.common_lib
貌似是这个包没有读取到
请问是我哪里少了配置吗

**Comment by Black-Knights** [comment]
报错日志
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/coder/vincent/series/common_lib/GlobalSettingKt;
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7251)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6787)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6704)
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7664)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                                                                                                    Caused by: androidx.startup.StartupException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/coder/vincent/series/common_lib/GlobalSettingKt;
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7246)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6787) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6704) 
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:223) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7664) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/coder/vincent/series/common_lib/GlobalSettingKt;
                                                                                                    	at com.coder.vincent.smart_dialog.SmartDialogInitializer.create(SmartDialogInitializer.kt:10)
                                                                                                    	at com.coder.vincent.smart_dialog.SmartDialogInitializer.create(SmartDialogInitializer.kt:8)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2388) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2358) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7246) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6787) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6704) 
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:223) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7664) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.coder.vincent.series.common_lib.GlobalSettingKt" on path: DexPathList[[zip file "/data/app/~~N42X6zo1cgm_mUnLxu1Fug==/包名.debug-zLxSFnuwmI8IMN5pV-cX7w==/base.apk"],nativeLibraryDirectories=[/data/app/~~N42X6zo1cgm_mUnLxu1Fug==/包名.debug-zLxSFnuwmI8IMN5pV-cX7w==/lib/arm64, /data/app/~~N42X6zo1cgm_mUnLxu1Fug==包名.debug-zLxSFnuwmI8IMN5pV-cX7w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.coder.vincent.smart_dialog.SmartDialogInitializer.create(SmartDialogInitializer.kt:10) 
                                                                                                    	at com.coder.vincent.smart_dialog.SmartDialogInitializer.create(SmartDialogInitializer.kt:8) 
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2388) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2358) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7246) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6787) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6704) 
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:223) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7664) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
>

**Comment by vincent-series** [comment]
> import com.coder.vincent.series.common_lib 貌似是这个包没有读取到 请问是我哪里少了配置吗

你好，这个版本的smart dialog 引用的common lib较低导致的，请使用最新版本，4.1.1.，如试用了其他我的库，尽量都保持最新版。

**Comment by vincent-series** [comment]
你应该是升级了smart toast 最新版，它依赖的common lib版本更高，所以与4.0.7的smart dialog 冲突了

**Comment by Black-Knights** [comment]
implementation "io.github.vincent-series:smart-toast:4.1.3"
implementation "io.github.vincent-series:smart-dialog:4.1.1"
这样引用没问题了
