### ISSUE TITLE
ToastScheduler中的 canReuseToast需要判断一下 toastConfig是否是同一类的，否则有可能出现强转异常

### ISSUE THREAD

**Issue by cai75951577** [vincent-series/smart-show#71]
ClassicToast 和 EmotionToast中各自继承了ToastConfig，如果app中 classic和emotion连着显示 就会出现此问题

**Comment by vincent-series** [comment]
> ClassicToast 和 EmotionToast中各自继承了ToastConfig，如果app中 classic和emotion连着显示 就会出现此问题

你好，应该不会。canReuseToast方法的参数是基类ToastConfig。另外alias的唯一性，保证不同类型的toast是不能复用的。你那边如果有碰到强转异常问题，可贴下堆栈信息，我这边分析下原因。

**Comment by konstant2016** [comment]
堆栈如下：

java.lang.ClassCastException: com.coder.vincent.smart_toast.alias.emotion.EmotionToast$Config cannot be cast to com.coder.vincent.smart_toast.alias.classic.ClassicToast$Config
at com.coder.vincent.smart_toast.alias.classic.ClassicToastFactory$produceToast$1.invoke(ClassicToastFactory.kt:17)
at com.coder.vincent.smart_toast.alias.classic.ClassicToastFactory$produceToast$1.invoke(ClassicToastFactory.kt:13)
at com.coder.vincent.smart_toast.compact.AbsCompactToast.updateConfig(AbsCompactToast.kt:22)
at com.coder.vincent.smart_toast.schedule.ToastScheduler.schedule(ToastScheduler.kt:28)
at com.coder.vincent.smart_toast.alias.emotion.EmotionToastInvoker.showHelper(EmotionToastInvoker.kt:184)
at com.coder.vincent.smart_toast.alias.emotion.EmotionToastInvoker.warning(EmotionToastInvoker.kt:50)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)

**Comment by vincent-series** [comment]
@cai75951577 @konstant2016 你好，bug已修复，请使用最新版本4.1.9

**Comment by konstant2016** [comment]
已经成功收到您的邮件
